version: "3"

services:
  server:
    image: c0d3m4513r1/rust-dc-bot:latest
    build:
      context: .
    container_name: rust-dc-bot
    restart: always
    volumes:
      - /share/Container/rust-dc-bot:/data
      - /etc/localtime:/etc/localtime:ro